### ISSUE TITLE
前端如何发布出来？

### ISSUE THREAD

**Issue by idragonet** [Asylumrots/OilStation#1]
后端已经发布。

**Comment by Asylumrots** [comment]
> 后端已经发布。

参考 https://github.com/Asylumrots/OilStation/blob/master/vue-OilStation/README-zh.md  下的Build Setup和发布

**Comment by idragonet** [comment]
> > 后端已经发布。
> 
> 参考 https://github.com/Asylumrots/OilStation/blob/master/vue-OilStation/README-zh.md 下的Build Setup和发布

谢谢！
